aliyun:
  # 阿里云的AccessKeyId
  accessKeyId: xxxx
  # 阿里云的AccessKeySecret
  accessKeySecret: xxxx
  # 域名的Endpoint，详情：https://api.aliyun.com/product/Domain
  # 地点            服务地址
  # 华东1（杭州）    domain.aliyuncs.com
  # 新加坡          domain-intl.aliyuncs.com
  domainEndpoint: domain.aliyuncs.com
  # dns的Endpoint，详情：https://api.aliyun.com/product/Alidns
  # 亚太地区
  # 地点            服务地址
  # 华北1（青岛）       dns.aliyuncs.com
  # 华北2（北京）       alidns.cn-beijing.aliyuncs.com
  # 华北3（张家口）     alidns.cn-zhangjiakou.aliyuncs.com
  # 华北5（呼和浩特）    alidns.cn-huhehaote.aliyuncs.com
  # 华北6（乌兰察布）    dns.aliyuncs.com
  # 华东1（杭州）       alidns.cn-hangzhou.aliyuncs.com
  # 华东2（上海）       alidns.cn-shanghai.aliyuncs.com
  # 华南1（深圳）       alidns.cn-shenzhen.aliyuncs.com
  # 西南1（成都）       alidns.cn-chengdu.aliyuncs.com
  # 中国（香港）        alidns.cn-hongkong.aliyuncs.com
  # 日本（东京）        alidns.ap-northeast-1.aliyuncs.com
  # 新加坡             alidns.ap-southeast-1.aliyuncs.com
  # 澳大利亚（悉尼）     alidns.ap-southeast-2.aliyuncs.com
  # 马来西亚（吉隆坡）   alidns.ap-southeast-3.aliyuncs.com
  # 印度尼西亚（雅加达） alidns.ap-southeast-5.aliyuncs.com
  # 欧洲与美洲
  # 美国（弗吉尼亚）     alidns.us-east-1.aliyuncs.com
  # 美国（硅谷）        alidns.us-west-1.aliyuncs.com
  # 英国（伦敦）        alidns.eu-west-1.aliyuncs.com
  # 德国（法兰克福）     alidns.eu-central-1.aliyuncs.com
  # 中东与印度
  # 印度（孟买）        alidns.ap-south-1.aliyuncs.com
  # 阿联酋（迪拜）      alidns.me-east-1.aliyuncs.com
  # 行业云
  # 华东1 金融云        alidns.cn-hangzhou-finance.aliyuncs.com
  # 华东2 金融云        alidns.cn-shanghai-finance-1.aliyuncs.com
  # 华南1 金融云        alidns.cn-shenzhen-finance-1.aliyuncs.com
  # 华北2 金融云（邀测） dns.aliyuncs.com
  dnsEndpoint: alidns.cn-shenzhen.aliyuncs.com

dns:
  - domain: www.toweron.top
    # 解析类型，只能填写 ipv4 和 ipv6 （注意全部小写且不能为大写）
    dnsType: ipv4
    ipv4:
      - 1.1.1.1

time:
  # 执行类型，可选值：single 和 repetition ，single：只执行一次，需要配合系统的定时任务执行。repetition重复执行，需要配合durationMinute配置项执行
  type: repetition
  # 时隔多久同步一次域名解析，单位为分钟
  durationMinute: 2m
